server:
  port: 3344

spring:
  application:
    name: microservicecloud-3344
  cloud:
    config:
      server:
        git:
          uri: https://github.com/fantastWang/microservicecloud-config.git
